# Generated by Django 4.2 on 2023-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_department_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='will_delete',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
