# Generated by Django 4.2 on 2023-04-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_department_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='test',
        ),
    ]
